//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ServiceVocabulary {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVocabulary.IVocabulary")]
    public interface IVocabulary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabulary/CheckCredential", ReplyAction="http://tempuri.org/IVocabulary/CheckCredentialResponse")]
        System.Nullable<int> CheckCredential(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabulary/CheckCredential", ReplyAction="http://tempuri.org/IVocabulary/CheckCredentialResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> CheckCredentialAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabulary/IsEmailAddressFree", ReplyAction="http://tempuri.org/IVocabulary/IsEmailAddressFreeResponse")]
        bool IsEmailAddressFree(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocabulary/IsEmailAddressFree", ReplyAction="http://tempuri.org/IVocabulary/IsEmailAddressFreeResponse")]
        System.Threading.Tasks.Task<bool> IsEmailAddressFreeAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVocabularyChannel : DAL.ServiceVocabulary.IVocabulary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VocabularyClient : System.ServiceModel.ClientBase<DAL.ServiceVocabulary.IVocabulary>, DAL.ServiceVocabulary.IVocabulary {
        
        public VocabularyClient() {
        }
        
        public VocabularyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VocabularyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocabularyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocabularyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<int> CheckCredential(string login, string password) {
            return base.Channel.CheckCredential(login, password);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> CheckCredentialAsync(string login, string password) {
            return base.Channel.CheckCredentialAsync(login, password);
        }
        
        public bool IsEmailAddressFree(string email) {
            return base.Channel.IsEmailAddressFree(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailAddressFreeAsync(string email) {
            return base.Channel.IsEmailAddressFreeAsync(email);
        }
    }
}
